# Generated by Django 5.1.3 on 2024-12-12 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlistitems',
            name='size',
        ),
    ]
