# Generated by Django 5.1.3 on 2024-12-12 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0002_remove_wishlistitems_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlistitems',
            name='wishlist',
        ),
        migrations.RemoveField(
            model_name='wishlistitems',
            name='product',
        ),
        migrations.DeleteModel(
            name='Wishlist',
        ),
        migrations.DeleteModel(
            name='Wishlistitems',
        ),
    ]
