# Generated by Django 5.1.3 on 2024-12-21 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coupons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupons',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='coupons',
            name='discount_value',
            field=models.IntegerField(max_length=10),
        ),
    ]
