# Generated by Django 5.1.3 on 2024-12-21 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coupons', '0002_alter_coupons_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupons',
            name='discount_value',
            field=models.IntegerField(),
        ),
    ]
