# Generated by Django 5.1.3 on 2025-01-09 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_alorderitem_created_at_alorderitem_updated_at'),
        ('transaction', '0004_alter_transactions_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.alorder'),
        ),
    ]
