# Generated by Django 5.1.3 on 2024-12-02 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_rename_userprofile_useraddress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='useraddress',
        ),
    ]
