# Generated by Django 5.1.3 on 2024-12-02 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraddress',
            name='address',
        ),
    ]
