"""
Django settings for ecommerce_project project.

Generated by 'django-admin startproject' using Django 3.2.19.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
from pathlib import Path
import cloudinary
import cloudinary.uploader
import cloudinary.api
import os





# Cloudinary API Configuration
cloudinary.config(
    cloud_name="du2duurgp",    # Replace with your Cloudinary cloud name
    api_key="342476421462729",          # Replace with your Cloudinary API key
    api_secret="3QrU0g0FSqGzOHZr2VAP5K72rD8"     # Replace with your Cloudinary API secret
)





# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


SITE_ID = 1

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-d1m7w(gff=85=en3jhhx_h6%6&-k@^hwq)e^rf67e2xaxlzs&y'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'auth_user',
    'admin_auth',
    'Catagory',
    'products',
    'userprofile',
    'cart',
    'order',
    'wishlist',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'cloudinary',
    'cloudinary_storage',
    'sweetify',
    "django_htmx",
    'Coupons',
    'transaction',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    "django_htmx.middleware.HtmxMiddleware",

]

ROOT_URLCONF = 'ecommerce_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS':[BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'wishlist.context_processors.cart_and_wishlist_counts',
                'cart.context_proccessers.search_context',

            ],
        },
    },
]

WSGI_APPLICATION = 'ecommerce_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.',
        'NAME': 'evara',
        'USER':'adhil',
        'PASSWORD':'123',
        'HOST':'LOCALHOST',
        'PORT':'5432'
    }
}

# Django Cloudinary storage for media files
DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'

# Cloudinary's base URL for media files

# Define where the media files will be stored
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


SWEETIFY_SWEETALERT_LIBRARY = 'sweetalert2'
# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / "static"] 
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')



# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# email setup
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

# SMTP Server Settings for Gmail
EMAIL_HOST = 'smtp.gmail.com' 
EMAIL_PORT = 587  
EMAIL_USE_TLS = True 
EMAIL_HOST_USER = 'adhilziyad780@gmail.com'  # Your Gmail address
EMAIL_HOST_PASSWORD = 'xjyd atpi uzpb ntjh' 
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER  
#xjyd atpi uzpb ntjh

AUTHENTICATION_BACKENDS = [
    'allauth.account.auth_backends.AuthenticationBackend', #for google
]
SOCIALACCOUNT_PROVIDERS = {
    'google':{
        'APP':{
            'client_id':'27598069188-44hj7n6r21dfbthj7tqhjaefvqvhv0ko.apps.googleusercontent.com',
            'secret':'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',
            'key':'',
        }
    }
}
LOGIN_URL = 'login'
LOGOUT_URL = 'logout'
LOGIN_REDIRECT_URL = 'index'
ACCOUNT_LOGOUT_REDIRECT_URL = 'login'


DATA_UPLOAD_MAX_MEMORY_SIZE = 20485760 
FILE_UPLOAD_MAX_MEMORY_SIZE = 20485760  #10MB 


RAZORPAY_KEY_ID = 'rzp_test_7btu5t0Ait7RKU'
RAZORPAY_KEY_SECRET = '32nD5E7G3IZycZS8T7vRJXZW'
