# Generated by Django 5.1.3 on 2024-11-25 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catagory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catagory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
