# Generated by Django 5.1.3 on 2024-11-25 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catagory', '0002_catagory_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catagory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
