# Generated by Django 5.1.3 on 2025-01-09 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catagory', '0005_alter_catagory_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catagory',
            name='offer',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
    ]
