# Generated by Django 5.1.3 on 2024-12-14 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_alorder_status'),
        ('userprofile', '0010_remove_useraddress_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alorder',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userprofile.useraddress'),
        ),
    ]
