# Generated by Django 5.1.3 on 2024-12-28 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_remove_alorder_coupon_alorderitem_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='alorder',
            name='razorpay_order_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
