# Generated by Django 5.1.3 on 2024-12-30 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alorder_razorpay_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='alorderitem',
            name='status',
            field=models.CharField(default='pending', max_length=10),
        ),
    ]
