# Generated by Django 5.1.3 on 2025-01-03 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_alorderitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='alorder',
            name='coupon',
            field=models.CharField(default='Not Applied', max_length=100),
        ),
    ]
