# Generated by Django 5.1.3 on 2025-01-03 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coupons', '0004_wallet'),
        ('order', '0009_alorder_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alorder',
            name='coupon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Coupons.coupons'),
        ),
    ]
