# Generated by Django 5.1.3 on 2025-01-07 01:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_alter_alorderitem_size_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='alorderitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alorderitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
