# Generated by Django 5.1.3 on 2025-01-11 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_alorderitem_created_at_alorderitem_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='alorder',
            name='real_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
    ]
