# Generated by Django 5.1.3 on 2024-12-07 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='offer',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
